server: 
  port: 9292
  
spring:  application:    name: HYSTRIX-DASHBOARD
    
hystrix:  dashboard:    proxy-stream-allow-list: "*"
    
    
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/        