server: 
  port: 9292
  
spring:  application:    name: HYSTRIX-DASHBOARD
  cloud:
    config:
      enabled: true
      uri: http://localhost:9296  
      
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka      
    
hystrix:  dashboard:    proxy-stream-allow-list: "*"
    
  