server: 
  port: 9292
  
spring:  application:    name: HYSTRIX-DASHBOARD
  cloud:
    config:
      enabled: true
      uri: http://localhost:9296  
    
hystrix:  dashboard:    proxy-stream-allow-list: "*"
    
  